name: 每日情报

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * *"

permissions:
  contents: read

jobs:
  run-daily-intel:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v5

      - name: 安装 Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: 查看仓库文件
        run: ls -la
